version: '3.9'

services:
  server:
    image: kentelinor/image-search-server:latest  # Pull from Docker Hub
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SEARCH_ENGINE_ID=${SEARCH_ENGINE_ID}
    ports:
      - "50051:50051"
    networks:
      - grpc-network

  client:
    image: kentelinor/image-search-client:latest  # Pull from Docker Hub
    depends_on:
      - server
    stdin_open: true                # Keep stdin open for interactive input
    tty: true                       # Allocate a pseudo-TTY
    networks:
      - grpc-network

  proxy:
    image: kentelinor/image-search-proxy:latest  # Pull from Docker Hub
    environment:
      - PYTHONPATH=/app:/app/generated:/app/client:/app/server  # Add /app/generated to PYTHONPATH
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - grpc-network

  frontend:
    image: kentelinor/image-search-frontend:latest  # Pull from Docker Hub
    ports:
      - "3000:80"
    networks:
      - grpc-network

  tests:
    image: kentelinor/image-search-tests:latest  # Pull from Docker Hub
    depends_on:
      - server  # Ensure the server is up before running tests
    networks:
      - grpc-network
    environment:
      - ENV_FILE=.env
    entrypoint: ["python", "-m", "unittest", "discover", "-s", "tests"]

networks:
  grpc-network:
    driver: bridge
